services:
  app:
    build: .
    container_name: social_app
    environment:
      DB_ADDR: "postgres://admin:adminpassword@db/social?sslmode=disable"
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: sh -c "swag init -g ./api/main.go -d cmd,internal && swag fmt && air -c .air.toml"
    restart: unless-stopped
    depends_on:
      - db


  db:
    image: postgres:15
    container_name: social_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: social
    ports:
      - "9565:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

  migrate:
    image: migrate/migrate
    volumes:
      - ./cmd/migrate/migrations:/migrations
    entrypoint: [ "migrate", "-path", "/migrations", "-database", "postgres://admin:adminpassword@db/social?sslmode=disable" ]
    depends_on:
      - db

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI
    restart: unless-stopped
    
volumes:
  pgdata: