services:
  app:
    image: golang:1.25
    container_name: social_app
    environment:
      DB_ADDR: "postgres://admin:adminpassword@db/social?sslmode=disable"
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: sh -c "go install github.com/air-verse/air@latest && air -c .air.toml"
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: social_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: social
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  pgdata: