services:
  app:
    build: .
    container_name: social_app
    environment:
      ENV: "prod"
      DB_ADDR: "postgres://admin:adminpassword@db/social?sslmode=disable"
      MAILHOG_ADDR: "mailhog:1025"
      REDIS_ADDR: "redis:6379"
      FROM_EMAIL: "gopher@email.com"
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: sh -c "swag init -g ./api/main.go -d cmd,internal && swag fmt && air -c .air.toml"
    restart: unless-stopped
    depends_on:
      - db


  db:
    image: postgres:16
    container_name: social_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: social
    ports:
      - "9565:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOST=redis
    ports:
      - "8081:8081"
    depends_on:
      - redis
    restart: unless-stopped


  migrate:
    image: migrate/migrate
    volumes:
      - ./cmd/migrate/migrations:/migrations
    entrypoint: [ "migrate", "-path", "/migrations", "-database", "postgres://admin:adminpassword@db/social?sslmode=disable" ]
    depends_on:
      - db

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI
    restart: unless-stopped

volumes:
  pgdata: